version: '3.8'


services:
  app:
    image: learningdocker/testjuly:0.0.1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/patient_db?autoReconnect=true&allowPublicKeyRetrieval=true&UseSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: OmSaiRam*369 
    depends_on:
      - db
      
  db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: OmSaiRam*369
      MYSQL_DATABASE: patient_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"